name: panwiz
on: push
jobs:
  convert_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check for 'pandoc.default.yml'"
        uses: andstor/file-existence-action@v1
        with:
          files: "pandoc.default.yml"
      - name: "Create output directory"
        run: mkdir output
      - name: "Convert files in custom pandoc environment"
        uses: "docker://christopher22/panwiz:latest"
        with:
          entrypoint: pandoc
          args: "--defaults=pandoc.default.yml"
# Instead of running my default template, you can create your own docker container on demand:
# Just remove the previous command and use:
#      - name: "Create custom environment: Set up QEMU"
#        uses: docker/setup-qemu-action@v1
#      - name: "Create custom environment: Set up Docker Buildx"
#        uses: docker/setup-buildx-action@v1
#        with:
#          driver: docker
#      - name: "Create custom environment: Build"
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: false
#          tags: cgundler/custom_pandoc_environment
#          file: .github/workflows/custom_pandoc_environment.dockerfile
#      - name: "Convert files in custom pandoc environment"
#        uses: addnab/docker-run-action@v1
#        with:
#          image: cgundler/custom_pandoc_environment:latest
#          run: "cd /document_root && pandoc --defaults=pandoc.default.yml"
#          options: "--volume=${{github.workspace}}:/document_root"
      - name: "Upload artifacts"
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
