name: panwiz
on: push
jobs:
  convert_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check for 'pandoc.default.yml'"
        uses: andstor/file-existence-action@v1
        with:
          files: "pandoc.default.yml"
      - name: "Create output directory"
        run: mkdir output
      - name: "Run pandoc"
        uses: docker://pandoc/latex
        with:
          args: "--defaults=pandoc.default.yml"
      - name: "Upload artifacts"
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
